openapi: "3.0.0"
info:
  title: The ECommerce App's API
  description: The Backend for My-Ecommerce App
  version: 1.0.0
  contact:
    email: aakash@ksenterprise.com
    url: "https://aakash@KsEmpire.com"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /home:
    get:
      tags:
        - Home
      summary: Returns a Greet Message from E-Commerce App
      responses:
        200:
          description: All Good !! Success !!
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: Internal Server Error
